class_name MapStreamer
extends Node3D
## Streams the Perth map around a target (the player's car).
##
## Tiles are 500 m squares generated by tools/osm_import into map/tiles/.
## Tiles within `view_radius` are drawn; tiles within `physics_radius` also get
## colliders. Loading happens on worker threads; colliders are added on the
## main thread, one tile per frame.
##
## World axes: X = east, Z = south (-Z = north), 1 unit = 1 metre, origin at
## the Little Shenton Lane townhouses in Northbridge.

signal map_ready
signal tile_loaded(key: Vector2i)
signal tile_unloaded(key: Vector2i)

@export var target_path: NodePath
@export var tiles_dir := "res://map/tiles"
## Move the target to the player's home when the map starts.
@export var place_target_at_spawn := true
@export var view_radius := 950.0
@export var physics_radius := 330.0
## Extra distance before a loaded tile is dropped again (stops flicker at edges).
@export var unload_margin := 200.0
@export var max_parallel_loads := 2
@export_group("Night lights")
## Real lights placed at the street lights nearest the target after dark.
@export var light_pool_size := 16
@export var light_range := 22.0
@export var light_energy := 3.0

var index: Dictionary = {}
var tile_size := 500.0

var _target: Node3D
var _materials: Dictionary = {}
var _props: Dictionary = {}
var _tiles: Dictionary = {}  # Vector2i -> {result: TileResult, collision: Node3D}
var _pending: Dictionary = {}  # Vector2i -> task id
var _results: Dictionary = {}  # Vector2i -> TileResult (finished on a worker)
var _collision_pending: Dictionary = {}  # Vector2i -> task id building that tile's colliders
var _collision_results: Dictionary = {}  # Vector2i -> [TileResult, collision holder] from a worker
var _mutex := Mutex.new()
var _night := 0.0
var _emissive: Array[ShaderMaterial] = []
const GLOSSY_AT_NIGHT: Array[StringName] = [&"water", &"facade_glass", &"rail_steel"]
var _light_pool: Array[OmniLight3D] = []
var _light_timer := 0.0
var _ready_emitted := false
var _overview: MapOverview
var _home: Node3D
var _settle_frames := 0  # physics frames until new colliders can be checked
const VOID_FRAMES := 90   # physics frames (0.75 s) with no ground off the map before stepping in
var _void_frames := 0
var _safe_timer := 0
var _last_safe := Transform3D()
var _has_last_safe := false
var _pools_on := true
var _traffic_sent := {}   # Vector2i -> true: tiles whose roads traffic already has
var _traffic_queue: Array[Dictionary] = []


func _ready() -> void:
	add_to_group(&"night_lights")
	index = _load_index()
	if index.is_empty():
		push_warning("MapStreamer: no map tiles found in %s (run tools/osm_import)" % tiles_dir)
		return
	tile_size = float(index.get("tile_size", 500.0))
	_load_materials()
	_props = MapProps.build_all(_materials)
	_make_light_pool()
	var overview := MapOverview.new()
	overview.name = "Overview"
	overview.near_cut = view_radius - 250.0
	if overview.load_from(tiles_dir.path_join("overview.p5o")):
		add_child(overview)
		_overview = overview
	else:
		overview.free()
	_place_home()
	_place_markers()
	_target = get_node_or_null(target_path) as Node3D
	if _target and place_target_at_spawn:
		_target.global_transform = get_spawn_transform()
		if _target is RigidBody3D:
			(_target as RigidBody3D).linear_velocity = Vector3.ZERO
			(_target as RigidBody3D).angular_velocity = Vector3.ZERO
	# Load the ground under the target right away so nothing falls through.
	var start := _focus_position()
	for key in _wanted(start, physics_radius):
		var result := MapTileLoader.build(_tile_path(key), _materials, _props)
		result.key = key
		_read_traffic(result)
		_finish_tile(result, true)


func _exit_tree() -> void:
	for key: Vector2i in _pending:
		WorkerThreadPool.wait_for_task_completion(_pending[key])
	_pending.clear()
	for key: Vector2i in _collision_pending:
		WorkerThreadPool.wait_for_task_completion(_collision_pending[key])
	_collision_pending.clear()
	for done: Array in _collision_results.values():
		(done[1] as Node).free()
	_collision_results.clear()


## Keeps the car on solid ground when it's moved somewhere the map hasn't
## loaded yet (a save restored, a teleport): that tile is built with colliders
## on the spot. A car with no ground under it at all (an old save from before
## the map existed, or one that slipped through) goes back home; one that
## drives off the end of the built map goes back to where it last drove.
## Runs before each physics step.
func _physics_process(_delta: float) -> void:
	if index.is_empty() or not (_target is RigidBody3D) or not is_instance_valid(_target):
		return
	var pos := _target.global_position
	var name := "%d_%d" % [tile_at(pos).x, tile_at(pos).y]
	if not index.get("tiles", {}).has(name):
		# Off the built map, past the end of a corridor. Only step in once the
		# car has had no ground under it for a moment, and put it back where
		# it last drove, facing back onto the map, rather than at home.
		_void_frames = _void_frames + 1 if _ground_below(pos).is_empty() else 0
		if _void_frames >= VOID_FRAMES:
			_void_frames = 0
			_reset_target(_last_safe if _has_last_safe else get_spawn_transform())
		return
	_void_frames = 0
	_safe_timer -= 1
	if _safe_timer <= 0 and _settle_frames == 0:
		_safe_timer = 30
		_remember_safe(pos)
	if not has_collision_at(pos):
		_load_now(pos)
	if pos.y < float(index.tiles[name].get("hmin", -50.0)) - 3.0:
		_reset_target(get_spawn_transform())  # below the lowest ground here
		return
	if _settle_frames > 0:
		_settle_frames -= 1
		if _settle_frames == 0 and _ground_below(pos).is_empty():
			_reset_target(get_spawn_transform())


func _process(delta: float) -> void:
	if index.is_empty():
		return
	_collect_finished()
	_send_traffic()
	var focus := _focus_position()
	_schedule_loads(focus)
	_unload_far(focus)
	_update_collision(focus)
	_light_timer -= delta
	if _light_timer <= 0.0:
		_light_timer = 0.3
		_update_light_pool(focus)
	if not _ready_emitted and _pending.is_empty():
		_ready_emitted = true
		map_ready.emit()


## Where the player starts: the Pop in the carport behind the townhouse on
## Little Shenton Lane (or on the lane outside, if the house isn't loaded).
func get_spawn_transform() -> Transform3D:
	var marker := StringName(index.get("home", {}).get("spawn_marker", ""))
	if _home and _home.has_method(&"has_marker") and _home.has_marker(marker):
		var t: Transform3D = _home.spawn_transform(marker)
		return Transform3D(Basis(Vector3.UP, t.basis.get_euler().y), t.origin + Vector3.UP * 0.6)
	var spawn: Dictionary = index.get("spawn", {})
	var p: Array = spawn.get("position", [0.0, 1.0, 0.0])
	return Transform3D(Basis(Vector3.UP, float(spawn.get("yaw", 0.0))), Vector3(p[0], p[1], p[2]))


## The player's townhouse (a HomeBase), or null.
func get_home() -> Node3D:
	return _home


## Named places (suburbs, squares) as world-space XZ positions.
func get_landmarks() -> Dictionary:
	var out := {}
	var marks: Dictionary = index.get("landmarks", {})
	for name: String in marks:
		var p: Array = marks[name]
		out[name] = Vector2(p[0], p[1])
	return out


## Points of interest for side activities (lookouts, beaches, servos,
## drive-thrus, quiet spots, landmarks), from index.json "pois". Each is a
## Dictionary: id, kind, name, suburb, p (Vector3, where to stop the car),
## yaw (the car's facing there, Basis(UP, yaw)), at (Vector3, the feature
## itself), and brand for servos and drive-thrus. `kind` filters by kind.
func get_pois(kind := "") -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for entry: Dictionary in index.get("pois", []):
		if kind != "" and entry.kind != kind:
			continue
		var poi := entry.duplicate()
		var p: Array = entry.p
		var at: Array = entry.get("at", p)
		poi.p = Vector3(p[0], p[1], p[2])
		poi.at = Vector3(at[0], at[1], at[2])
		out.append(poi)
	return out


## Tile key containing a world position.
func tile_at(world_pos: Vector3) -> Vector2i:
	return Vector2i(floori(world_pos.x / tile_size), floori(-world_pos.z / tile_size))


func is_tile_loaded(key: Vector2i) -> bool:
	return _tiles.has(key)


func has_collision_at(world_pos: Vector3) -> bool:
	var key := tile_at(world_pos)
	return _tiles.has(key) and _tiles[key].collision != null


func loaded_tile_count() -> int:
	return _tiles.size()


## Called by EnvironmentController (night_lights group): 0 = day, 1 = night.
func set_night_amount(amount: float) -> void:
	_night = amount
	for material in _emissive:
		var name := material.resource_name
		var energy := 5.0 if name == "light_head" else 1.4
		material.set_shader_parameter("emission_energy", amount * energy)
	var pool: Mesh = _props.get(&"light_pool")
	if pool:
		(pool.surface_get_material(0) as ShaderMaterial).set_shader_parameter("energy", amount * 0.8)
	if (amount > 0.02) != _pools_on:
		_pools_on = amount > 0.02
		get_tree().call_group(&"map_light_pools", &"set_visible", _pools_on)
	if _overview and _overview.mesh:
		var m := _overview.mesh.surface_get_material(0) as ShaderMaterial
		m.set_shader_parameter("brightness", lerpf(0.95, 0.07, amount))
		var tm := _overview.tower_material()
		if tm:
			tm.set_shader_parameter("brightness", lerpf(0.95, 0.09, amount))
			tm.set_shader_parameter("night", amount)
	# Glossy surfaces (the river, glass towers, rails) reflect a daylight
	# sky at night (the sky's reflection map lags the night sky), so they go
	# matte and darker as night falls.
	for gloss_name: StringName in GLOSSY_AT_NIGHT:
		var m := _materials.get(gloss_name) as ShaderMaterial
		if m == null:
			continue
		# (A null meta value erases the key, so unset parameters store their default.)
		if not m.has_meta("day_roughness"):
			var r: Variant = m.get_shader_parameter("roughness")
			var mt: Variant = m.get_shader_parameter("metallic")
			m.set_meta("day_roughness", 0.4 if r == null else float(r))
			m.set_meta("day_metallic", 0.0 if mt == null else float(mt))
		m.set_shader_parameter("roughness", lerpf(float(m.get_meta("day_roughness")), 0.95, amount))
		m.set_shader_parameter("metallic", lerpf(float(m.get_meta("day_metallic")), 0.0, amount))
	var water := _materials.get(&"water") as ShaderMaterial
	if water:
		water.set_shader_parameter("albedo_color", Color.WHITE.lerp(Color(0.35, 0.4, 0.5), amount))


## Build the tiles around `pos` with colliders right now (blocking).
func _load_now(pos: Vector3) -> void:
	for key in _wanted(pos, minf(physics_radius, tile_size)):
		if _collision_pending.has(key):
			WorkerThreadPool.wait_for_task_completion(_collision_pending[key])
			_collision_pending.erase(key)
			_collect_collision(true)
		if _tiles.has(key):
			if _tiles[key].collision == null:
				_add_collision(_tiles[key])
			continue
		if _pending.has(key):
			WorkerThreadPool.wait_for_task_completion(_pending[key])
			_pending.erase(key)
			_collect_finished()
			if _tiles.has(key) and _tiles[key].collision == null:
				_add_collision(_tiles[key])
			continue
		var result := MapTileLoader.build(_tile_path(key), _materials, _props)
		result.key = key
		_read_traffic(result)
		_finish_tile(result, true)
	# New colliders are only queryable after the next physics step.
	_settle_frames = maxi(_settle_frames, 3)


## Ground straight under `pos` (not above it, so tunnels and car parks work).
## Remembers where the car last sat upright on loaded ground, facing back the
## way it came, for _physics_process to return it to.
func _remember_safe(pos: Vector3) -> void:
	var body := _target as RigidBody3D
	if body.global_basis.y.dot(Vector3.UP) < 0.9 or not has_collision_at(pos):
		return
	var hit := _ground_below(pos)
	if hit.is_empty() or pos.y - (hit.position as Vector3).y > 2.0:
		return
	var back := Basis(Vector3.UP, body.global_rotation.y + PI)
	_last_safe = Transform3D(back, pos + Vector3.UP * 0.3)
	_has_last_safe = true


func _ground_below(pos: Vector3) -> Dictionary:
	var query := PhysicsRayQueryParameters3D.create(pos + Vector3.UP, pos + Vector3.DOWN * 80.0, 1)
	query.exclude = [(_target as CollisionObject3D).get_rid()]
	return get_world_3d().direct_space_state.intersect_ray(query)


func _reset_target(t: Transform3D) -> void:
	var body := _target as RigidBody3D
	body.global_transform = t
	body.linear_velocity = Vector3.ZERO
	body.angular_velocity = Vector3.ZERO


# --- placed scenes and markers -----------------------------------------------

func _placed_transform(entry: Dictionary) -> Transform3D:
	var p: Array = entry.get("position", [0.0, 0.0, 0.0])
	return Transform3D(Basis(Vector3.UP, float(entry.get("yaw", 0.0))), Vector3(p[0], p[1], p[2]))


## The townhouse is a hand-built scene; the importer levels its block and
## leaves OSM's buildings off it.
func _place_home() -> void:
	var entry: Dictionary = index.get("home", {})
	var path: String = entry.get("scene", "")
	if path == "" or not ResourceLoader.exists(path):
		return
	_home = (load(path) as PackedScene).instantiate() as Node3D
	_home.name = "Home"
	_home.transform = _placed_transform(entry)
	add_child(_home)


## Job sites, badges and workshop bays (docs/HOOKS.md). They stay loaded everywhere so
## jobs can be offered for places that aren't streamed in yet.
func _place_markers() -> void:
	for entry: Dictionary in index.get("job_sites", []):
		var site := JobSite.new()
		site.name = "Site_" + str(entry.id)
		site.site_id = entry.id
		site.display_name = entry.get("name", "")
		site.suburb = entry.get("suburb", "")
		if entry.has("kinds"):
			site.kinds = PackedStringArray(entry.kinds)
		site.transform = _placed_transform(entry)
		add_child(site)
	for entry: Dictionary in index.get("badges", []):
		var badge := Collectible.new()
		badge.name = "Badge_" + str(entry.id)
		badge.badge_id = entry.id
		badge.transform = _placed_transform(entry)
		add_child(badge)
	for entry: Dictionary in index.get("workshops", []):
		var spot := WorkshopSpot.new()
		spot.name = "Workshop_" + str(entry.id)
		spot.spot_id = entry.id
		spot.display_name = entry.get("name", "")
		spot.kinds = PackedStringArray(entry.get("kinds", ["parts", "tuning"]))
		if entry.has("color"):
			var c: Array = entry.color
			spot.color = Color(c[0], c[1], c[2])
		spot.transform = _placed_transform(entry)
		add_child(spot)


# --- loading -----------------------------------------------------------------

func _load_index() -> Dictionary:
	var path := tiles_dir.path_join("index.json")
	if not FileAccess.file_exists(path):
		return {}
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	return parsed if parsed is Dictionary else {}


func _load_materials() -> void:
	for name: String in index.get("materials", []):
		var path := "res://map/materials/%s.tres" % name
		if not ResourceLoader.exists(path):
			continue
		var material := load(path) as Material
		_materials[StringName(name)] = material
		if material is ShaderMaterial and material.get_shader_parameter("emission_texture") != null:
			_emissive.append(material)


func _tile_path(key: Vector2i) -> String:
	return tiles_dir.path_join("%d_%d.p5t" % [key.x, key.y])


func _focus_position() -> Vector3:
	if _target and is_instance_valid(_target):
		return _target.global_position
	var camera := get_viewport().get_camera_3d() if is_inside_tree() else null
	return camera.global_position if camera else Vector3.ZERO


## Tiles whose square is within `radius` of `pos`, nearest first.
func _wanted(pos: Vector3, radius: float) -> Array[Vector2i]:
	var tiles: Dictionary = index.get("tiles", {})
	var east := pos.x
	var north := -pos.z
	var out: Array[Vector2i] = []
	var dist := {}
	var reach := ceili(radius / tile_size)
	var center := tile_at(pos)
	for i in range(center.x - reach, center.x + reach + 1):
		for j in range(center.y - reach, center.y + reach + 1):
			if not tiles.has("%d_%d" % [i, j]):
				continue
			var d := _distance_to_tile(east, north, i, j)
			if d <= radius:
				var key := Vector2i(i, j)
				out.append(key)
				dist[key] = d
	out.sort_custom(func(a: Vector2i, b: Vector2i) -> bool: return dist[a] < dist[b])
	return out


func _distance_to_tile(east: float, north: float, i: int, j: int) -> float:
	var dx := maxf(maxf(i * tile_size - east, east - (i + 1) * tile_size), 0.0)
	var dz := maxf(maxf(j * tile_size - north, north - (j + 1) * tile_size), 0.0)
	return sqrt(dx * dx + dz * dz)


func _schedule_loads(focus: Vector3) -> void:
	for key in _wanted(focus, view_radius):
		if _pending.size() >= max_parallel_loads:
			return
		if _tiles.has(key) or _pending.has(key) or _results.has(key):
			continue
		var path := _tile_path(key)
		_pending[key] = WorkerThreadPool.add_task(_load_worker.bind(key, path), false, "map tile")


func _load_worker(key: Vector2i, path: String) -> void:
	var result := MapTileLoader.build(path, _materials, _props)
	result.key = key
	_read_traffic(result)
	_mutex.lock()
	_results[key] = result
	_mutex.unlock()


func _collect_finished() -> void:
	for key: Vector2i in _pending.keys():
		var task: int = _pending[key]
		if WorkerThreadPool.is_task_completed(task):
			WorkerThreadPool.wait_for_task_completion(task)
			_pending.erase(key)
	_mutex.lock()
	var done := _results.duplicate()
	_results.clear()
	_mutex.unlock()
	for key: Vector2i in done:
		_finish_tile(done[key], false)


func _finish_tile(result: MapTileLoader.TileResult, with_collision: bool) -> void:
	if result.error != "":
		push_warning("MapStreamer: " + result.error)
		return
	if _tiles.has(result.key):
		result.root.free()
		return
	add_child(result.root)
	var glow := result.root.get_node_or_null(^"light_pools")
	if glow:
		glow.visible = _pools_on
	if not result.traffic.is_empty() and not _traffic_sent.has(result.key):
		_traffic_sent[result.key] = true
		_traffic_queue.append(result.traffic)
	var entry := {result = result, collision = null}
	_tiles[result.key] = entry
	if with_collision:
		_add_collision(entry)
	tile_loaded.emit(result.key)


func _add_collision(entry: Dictionary) -> void:
	var result: MapTileLoader.TileResult = entry.result
	var holder := MapTileLoader.make_collision(result)
	result.root.add_child(holder)
	entry.collision = holder


## Colliders for tiles coming into range are built on a worker (baking the
## concave shapes takes tens of milliseconds a tile); the main thread only
## adds the finished bodies, one tile a frame.
func _update_collision(focus: Vector3) -> void:
	_collect_collision(false)
	var east := focus.x
	var north := -focus.z
	for key: Vector2i in _tiles:
		var entry: Dictionary = _tiles[key]
		var d := _distance_to_tile(east, north, key.x, key.y)
		if entry.collision == null and d <= physics_radius:
			if not _collision_pending.has(key) and not _collision_results.has(key) \
					and _collision_pending.size() < max_parallel_loads:
				var result: MapTileLoader.TileResult = entry.result
				_collision_pending[key] = WorkerThreadPool.add_task(
					_collision_worker.bind(key, result), false, "map tile collision")
		elif entry.collision != null and d > physics_radius + unload_margin:
			entry.collision.queue_free()
			entry.collision = null


func _collision_worker(key: Vector2i, result: MapTileLoader.TileResult) -> void:
	var holder := MapTileLoader.make_collision(result)
	_mutex.lock()
	_collision_results[key] = [result, holder]
	_mutex.unlock()


## Adds colliders finished on a worker: one tile a frame, or all of them.
func _collect_collision(all: bool) -> void:
	for key: Vector2i in _collision_pending.keys():
		if WorkerThreadPool.is_task_completed(_collision_pending[key]):
			WorkerThreadPool.wait_for_task_completion(_collision_pending[key])
			_collision_pending.erase(key)
	_mutex.lock()
	var keys := _collision_results.keys()
	_mutex.unlock()
	for key: Vector2i in keys:
		_mutex.lock()
		var done: Array = _collision_results[key]
		_collision_results.erase(key)
		_mutex.unlock()
		var holder: Node3D = done[1]
		var entry: Dictionary = _tiles.get(key, {})
		# The tile may have been unloaded, reloaded or given colliders meanwhile.
		if entry.is_empty() or entry.result != done[0] or entry.collision != null:
			holder.free()
			continue
		entry.result.root.add_child(holder)
		entry.collision = holder
		if not all:
			return


func _unload_far(focus: Vector3) -> void:
	var east := focus.x
	var north := -focus.z
	for key: Vector2i in _tiles.keys():
		if _distance_to_tile(east, north, key.x, key.y) > view_radius + unload_margin:
			var entry: Dictionary = _tiles[key]
			entry.result.root.queue_free()
			_tiles.erase(key)
			tile_unloaded.emit(key)


# --- traffic -----------------------------------------------------------------

## Road data for the traffic system (docs/TRAFFIC.md), read with the tile.
## Traffic keeps roads once it has them, so each tile is sent only once.
func _read_traffic(result: MapTileLoader.TileResult) -> void:
	var entry: Dictionary = index.get("tiles", {}).get("%d_%d" % [result.key.x, result.key.y], {})
	if entry.has("traffic"):
		result.traffic = MapTileLoader.read(tiles_dir.path_join(entry.traffic))


## Sent from _process so the traffic manager has joined its group by then.
func _send_traffic() -> void:
	if _traffic_queue.is_empty():
		return
	var data: Dictionary = _traffic_queue.pop_front()  # one tile per frame
	get_tree().call_group(&"traffic", &"add_network", data)


# --- night lights ------------------------------------------------------------

func _make_light_pool() -> void:
	for i in light_pool_size:
		var light := OmniLight3D.new()
		light.name = "StreetLight%d" % i
		light.light_color = Color(1.0, 0.74, 0.45)
		light.omni_range = light_range
		light.omni_attenuation = 1.3
		light.shadow_enabled = false
		light.visible = false
		add_child(light)
		_light_pool.append(light)


func _update_light_pool(focus: Vector3) -> void:
	if _night < 0.05:
		for light in _light_pool:
			light.visible = false
		return
	var candidates: Array[Vector3] = []
	for key: Vector2i in _tiles:
		var result: MapTileLoader.TileResult = _tiles[key].result
		for p in result.lights:
			if absf(p.x - focus.x) < 160.0 and absf(p.z - focus.z) < 160.0:
				candidates.append(p)
	candidates.sort_custom(func(a: Vector3, b: Vector3) -> bool:
		return a.distance_squared_to(focus) < b.distance_squared_to(focus))
	for i in _light_pool.size():
		var light := _light_pool[i]
		light.visible = i < candidates.size()
		if light.visible:
			light.global_position = candidates[i] + Vector3(0, -0.5, 0)
			light.light_energy = light_energy * _night
